services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "yarn && yarn start"
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true