version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "yarn && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true